### ISSUE TITLE
support bayesian estimation methods

### ISSUE THREAD

**Issue by jamalsenouci** [jamalsenouci/causalimpact#10]
A major difference between the R version and this is the method of estimation. Currently this only supports maximum likelihood estimation and results in differences between the two packages as noticed in #7

**Comment by JackZYSun** [comment]
Hi, does the package support Bayesian estimation methods now? or still just MLE?

**Comment by jamalsenouci** [comment]
initial support for bayesian estimation added, enhancements will be tracked under separate issues
