### ISSUE TITLE
How to get P-value in Python version?

### ISSUE THREAD

**Issue by jingwen66** [jamalsenouci/causalimpact#12]
Summary of R package provides "Posterior tail-area probability p" and "Posterior prob. of a causal effect". I cannot find it in summary of python package. Is there any reason of not reporting them?

**Comment by jamalsenouci** [comment]
No reason other than it hasn't been implemented yet due to lack of time

**Comment by jingwen66** [comment]
Is it possible to get it implemented in near future :)

**Comment by jamalsenouci** [comment]
Possibly but I'm not sure exactly when I'll next have time to work on it

**Comment by Worerlz** [comment]
Hi,
I've implemented this p-value and I used the same technique describe in the paper.
`post_inf = impact.inferences[post_period[0]:post_period[1]]
step_x = np.random.randint(2, size=len(post_inf.index) * 1000)
step_x[step_x == 0] = -1
x = post_inf['point_pred'].repeat(1000) + abs(post_inf['point_pred'].repeat(
    1000) - post_inf['point_pred_upper'].repeat(1000)) * np.random.random(size=len(post_inf.index) * 1000)
aciertos = post_inf['response'].repeat(1000) - x > 0

goals_f = aciertos.sum() / (len(post_inf.index) * 1000)`

Hope this will be useful

**Comment by wmelton** [comment]
@Worerlz You should submit a pull request so if it works it can be merged in to Master upon @jamalsenouci approval

**Comment by WillianFuks** [comment]
Hi @jamalsenouci , just wondering, do you know how we can implement the computation of the p-value in this version of python? Maybe with some guidance we can contribute to the project. 

Google's code uses an average over several samples, not sure how the same could be implemented here (or even if @Worerlz suggestion already does the trick)

**Comment by jamalsenouci** [comment]
I have attempted a p-value implementation in the latest version. This will need updating when the bayesian estimation is done but should do for now.
