### ISSUE TITLE
CSV Data?

### ISSUE THREAD

**Issue by Jamiedee90** [jamalsenouci/causalimpact#14]
Hi,

If I wanted it to read from a CSV file:

data = pd.read_csv('Traffic.csv',header=None,names = ['CountryX','CountryY'])

where would I need to save the file for it read this?

Many Thanks
JD

**Comment by Jamiedee90** [comment]
Hi @rpanai 

apologies, this was just a dummy line of code. this is to replace the lines:

_np.random.seed(1)

x1 = arma_generate_sample(ar=[0.999], ma=[0.9], nsample=100) + 100
y = 1.2 * x1 + np.random.randn(100)

y[71:100] = y[71:100] + 10
data = pd.DataFrame(np.array([y, x1]).T, columns=["y","x1"])_

This makes it easier to update the data and re use the test across different clients

**Comment by jamalsenouci** [comment]
You can save it wherever you want as long as you reference the path in pd.read_csv. In your example traffic.csv would be located in the same directory you are running the code from.
