### ISSUE TITLE
AttributeError: 'CausalImpact' object has no attribute 'inferences'

### ISSUE THREAD

**Issue by AInhoa84** [jamalsenouci/causalimpact#24]
Hello,

I am trying to use this package, following the steps in your notebook:  https://github.com/jamalsenouci/causalimpact/blob/master/GettingStarted.ipynb

I have successfully installed the package in Power Shell:
![1git_installation](https://user-images.githubusercontent.com/45105413/148213907-ca451ab5-f783-4195-aff6-8ff75ba78b93.PNG)

And this is how my notebook looks like:
![2](https://user-images.githubusercontent.com/45105413/148214074-b04c64ae-7569-4ef0-a903-a4e57460eff5.PNG)

However, when I try to run the package, these are the errors I get:
![3](https://user-images.githubusercontent.com/45105413/148214260-fe210674-1060-4a62-8079-ecae2e5ffe39.PNG)
![4](https://user-images.githubusercontent.com/45105413/148214264-f1ccf039-2dc8-4f9e-b8ac-1047e41de99f.PNG)

Can you please help me figure out what I am doing wrong please?

Thank you in advance and Happy New Year!

AInhoa

**Comment by AInhoa84** [comment]
I forgot to attach the csv file that I am using, here it goes:
[example_Github.csv](https://github.com/jamalsenouci/causalimpact/files/7814729/example_Github.csv)

**Comment by jamalsenouci** [comment]
[AInhoa84](https://github.com/AInhoa84) this should be fixed now
