### ISSUE TITLE
ImportError: No module named tests.test

### ISSUE THREAD

**Issue by reventropy** [jamalsenouci/causalimpact#4]
It's no problem if I just comment out the import in __init__ but I thought you might want to know about the error.

File "/usr/local/lib/python2.7/dist-packages/causalimpact-0.1-py2.7.egg/causalimpact/__init__.py", line 10, in <module>
    from causalimpact.tests.test import run as test  # noqa
ImportError: No module named tests.test

**Comment by jamalsenouci** [comment]
this should be fixed now thanks for the heads up
