### ISSUE TITLE
ImportError: cannot import name 'PandasError'

### ISSUE THREAD

**Issue by ventouris** [jamalsenouci/causalimpact#5]
Using Pandas 0.20.1, when I try to import CausalImpact package, I get the following error

`ImportError: cannot import name 'PandasError'`

**Comment by jamalsenouci** [comment]
pandas 0.20 isn't supported yet, you would have to use pandas 0.19.2 or lower for the moment.

**Comment by jamalsenouci** [comment]
actually I just made the change, it was only small
